import { Module } from '@nestjs/common';
import {
  AppConfigService,
  APP_ENV,
  BINANCE_API_KEY,
  BINANCE_API_SECRET,
  POSTGRES_DATABASE,
  POSTGRES_HOST,
  POSTGRES_PASSWORD,
  POSTGRES_PORT,
  POSTGRES_USERNAME,
  HTTP_PORT,
  TOKEN_PAIR,
  RISK_MODULE_RANGE,
  RISK_MODULE_STEPS,
  TIMEFRAME_MINUTES,
  BASE_PRICE,
  ENTRY_LONG,
  ENTRY_SHORT,
  MIN_PROBABILITY,
  TP_STRATEGY,
  FIXED_RR_RATIO,
  CAPITAL,
  LEVERAGE,
  POSITION_SIZE,
  MARGIN_TYPE,
  MAX_DAILY_LOSS,
  MAX_CONSECUTIVE_LOSS,
  MAX_DAILY_TRADES,
  MAX_OPEN_POSITIONS,
  PREDICTION_UPDATE_INTERVAL_MS,
  IN_POSITION_CHECK_INTERVAL_MS,
} from './app-config.service';
import { ConfigModule } from '@nestjs/config';
import * as Joi from 'joi';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: '.env',
      validationSchema: Joi.object({
        [APP_ENV]: Joi.string().required(),
        [HTTP_PORT]: Joi.string().required(),
        [TOKEN_PAIR]: Joi.string().required(),
        [BINANCE_API_KEY]: Joi.string().required(),
        [BINANCE_API_SECRET]: Joi.string().required(),
        [POSTGRES_HOST]: Joi.string().required(),
        [POSTGRES_PORT]: Joi.number().required(),
        [POSTGRES_USERNAME]: Joi.string().required(),
        [POSTGRES_PASSWORD]: Joi.string().required(),
        [POSTGRES_DATABASE]: Joi.string().required(),
        [RISK_MODULE_STEPS]: Joi.string().required(),
        [RISK_MODULE_RANGE]: Joi.string().required(),
        [TIMEFRAME_MINUTES]: Joi.string().required(),
        [BASE_PRICE]: Joi.string().required(),
        [ENTRY_LONG]: Joi.string().required(),
        [ENTRY_SHORT]: Joi.string().required(),
        [MIN_PROBABILITY]: Joi.string().required(),
        [TP_STRATEGY]: Joi.string().required(),
        [FIXED_RR_RATIO]: Joi.string().required(),
        [CAPITAL]: Joi.string().required(),
        [LEVERAGE]: Joi.string().required(),
        [POSITION_SIZE]: Joi.string().required(),
        [MARGIN_TYPE]: Joi.string().required(),
        [MAX_DAILY_LOSS]: Joi.string().required(),
        [MAX_CONSECUTIVE_LOSS]: Joi.string().required(),
        [MAX_DAILY_TRADES]: Joi.string().required(),
        [MAX_OPEN_POSITIONS]: Joi.string().required(),
        [PREDICTION_UPDATE_INTERVAL_MS]: Joi.string().required(),
        [IN_POSITION_CHECK_INTERVAL_MS]: Joi.string().required(),
      }),
    }),
  ],
  controllers: [],
  providers: [AppConfigService],
  exports: [AppConfigService],
})
export class AppConfigModule {}
